name: quran_companion
description: A comprehensive Quran reader and study tool
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core packages
  http: ^1.1.0
  provider: ^6.0.5
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Audio
  just_audio: ^0.10.4
  audio_session: ^0.1.18
  just_audio_background: ^0.0.1-beta.17
  
  # Location & Maps
  geolocator: ^10.1.0
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  permission_handler: ^11.0.1
  
  # Islamic tools
  adhan: ^2.0.0-nullsafety.2
  # flutter_qiblah: ^2.2.0  # Temporarily disabled due to namespace issues
  
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  
  # Utils
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.1
  flutter_native_splash: ^2.3.8
  # flutter_local_notifications: ^16.3.3  # Temporarily disabled due to compilation error
  dio: ^5.4.0
  flutter_file_dialog: ^3.0.2
  timezone: ^0.9.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
    - assets/images/
          
  generate: true