name: Build Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: |
        cd quran_companion
        flutter pub get
        
    - name: Build APK
      run: |
        cd quran_companion
        flutter build apk --release --split-per-abi
        
    - name: Build App Bundle
      run: |
        cd quran_companion
        flutter build appbundle --release
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: |
          quran_companion/build/app/outputs/flutter-apk/*.apk
          quran_companion/build/app/outputs/bundle/release/*.aab

  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: |
        cd quran_companion
        flutter pub get
        
    - name: Build iOS
      run: |
        cd quran_companion
        flutter build ios --release --no-codesign
        
    - name: Create IPA
      run: |
        cd quran_companion
        mkdir -p build/ios/ipa
        cp -r build/ios/iphoneos/Runner.app build/ios/ipa/
        cd build/ios/ipa
        zip -r ../Runner.ipa .
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa
        path: quran_companion/build/ios/Runner.ipa

  create-release:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Android artifacts
      uses: actions/download-artifact@v3
      with:
        name: android-apk
        path: ./android-release/
        
    - name: Download iOS artifacts
      uses: actions/download-artifact@v3
      with:
        name: ios-ipa
        path: ./ios-release/
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./android-release/*
          ./ios-release/*
        generate_release_notes: true
        draft: false
        prerelease: false
